---
title: "ACH et CAH pour activpro"
output: html_notebook
---
# Création base pour ACM et CAH

```{r}
na_Adm10_id = baseline$nepp3[which(is.na(baseline$Adm10))]
na_Adm11_id = baseline$nepp3[which(is.na(baseline$Adm11))]
na_Adm12_id = baseline$nepp3[which(is.na(baseline$Adm12))]
na_Adm12a_id = baseline$nepp3[which(is.na(baseline$Adm12a))]
na_actproBl_id = unique(c(na_Adm10_id,na_Adm11_id,na_Adm12_id,na_Adm12a_id))
```

```{r}
actproBl = baseline[-which(baseline$nepp3 %in% na_actproBl_id),c("nepp3","Adm10","Adm11","Adm12","Adm12a") ]
```
```{r}
dim(actproBl)
```

```{r}
colnames(actproBl)
```

```{r}
colnames(baseline)[1]
colnames(baseline)[25]
colnames(baseline)[27]
colnames(baseline)[29]
colnames(baseline)[30]
colnames(baseline)[594]
colnames(baseline)[595]
```
```{r}
dim(baseline)[1] - dim(actproBl)[1]
```



# ACM

```{r}
ACM_activpro = MCA(actproBl[,c("Adm10","Adm11","Adm12a","Adm12")], graph = F)
```
```{r}
ACM_activpro$eig
```

# CAH

```{r}
cah_activpro = HCPC(ACM_activpro,graph = FALSE)
```

```{r}
plot(cah_activpro, choice = "tree")
```
```{r}
plot(cah_activpro, choice = "3D.map")
```
```{r}
plot(cah_activpro, choice = "bar")
```
```{r}
plot(cah_activpro, choice = "map")
```




# Ajout dans la base

```{r}
actproBl$cah_activpro = as.factor(cah_activpro$data.clust$clust)
```

4 = retraite
1 = travail
2 = chomeur
3 = inactif

```{r}
actproBl$cah_activproName[which(actproBl$cah_activpro == 1)] = "T"
actproBl$cah_activproName[which(actproBl$cah_activpro == 2)] = "C"
actproBl$cah_activproName[which(actproBl$cah_activpro == 3)] = "I"
actproBl$cah_activproName[which(actproBl$cah_activpro == 4)] = "R"
```

```{r}
actproBl$cah_activproName = as.factor(actproBl$cah_activproName)
actproBl$cah_activproName = relevel(actproBl$cah_activproName , ref = "T")
```

```{r}
colnames(actproBl)
```

```{r}
baseline$activproCAH = 0
for(k in baseline$nepp3){
  if(k %in% na_actproBl_id)
    baseline$activproCAH[which(baseline$nepp3 == k)] = NA
  else
    baseline$activproCAH[which(baseline$nepp3 == k)] = actproBl$cah_activpro[which(actproBl$nepp3 == k)]
}

baseline$activproCAH = as.character(baseline$activproCAH)
baseline$activproCAH[which(baseline$activproCAH == 1)] = "T"
baseline$activproCAH[which(baseline$activproCAH == 2)] = "C"
baseline$activproCAH[which(baseline$activproCAH == 3)] = "I"
baseline$activproCAH[which(baseline$activproCAH == 4)] = "R"
baseline$activproCAH = as.factor(baseline$activproCAH)
```

```{r}
baseline$activproCAH = relevel(baseline$activproCAH , ref = "T")
levels(baseline$activproCAH) = c(levels(baseline$activproCAH), "NSP")
levels(baseline$activproCAH)
```


```{r}
summary(actproBl$cah_activproName)
summary(baseline$activproCAH)
```
```{r}
colnames(actproBl)
```
```{r}
test = actproBl[,c("Adm10","Adm11","Adm12a","Adm12","cah_activpro")]
colnames(test)
```


```{r}
catdes(test, num.var = 5)

```
```{r}
testbis = test[which(baseline$activproBis == "NSP"),]
```
```{r}
catdes(testbis, num.var = 5)
```







