##Codage activproBis

```{r}
baseline$activproBis = 0

for (j in 1:(dim(baseline)[1])){
  
  ## 9
  if (is.na(baseline$Adm12a[j]))
    baseline$activproBis[j] = NA
  
  ## 1
  else if (baseline$Adm12a[j] == "JNNN" & baseline$Adm11[j] == 0)
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "JNNN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] == 54)
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "JNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 85)
    baseline$activproBis[j] = "I"

   ## 2
  else if (baseline$Adm12a[j] == "N98N" & baseline$Adm11[j] == 0 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 77)
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "N98N" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 77)
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "N98N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,74))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "N98N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNN3NN" & baseline$Adm10[j] == 85)
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "N98N" & baseline$Adm11[j] == 5 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 85)
    baseline$activproBis[j] = "I"
  
  ## 3
  else if(baseline$Adm12a[j] == "N9N7")
    baseline$activproBis[j] = "R"
  
  ## 4
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 0)
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNN3NN" & baseline$Adm10[j] == 86)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,86))
    baseline$activproBis[j] = "I"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 2 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,86))
    baseline$activproBis[j] = "I"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 2 & baseline$Adm12[j] %in% c("N5N3NN", "N5NNNN") & baseline$Adm10[j] %in% c(85,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,86))
    baseline$activproBis[j] = "I"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "N5NNNN" & baseline$Adm10[j] == 95)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,86))
    baseline$activproBis[j] = "I"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & (baseline$Adm10[j] %in% c(54,74,77) | is.na(baseline$Adm10[j])))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "N9NN" & baseline$Adm11[j] == 5)
    baseline$activproBis[j] = "I"
  
  ## 5
  else if (baseline$Adm12a[j] == "NN87" & baseline$Adm11[j] == 0)
    baseline$activproBis[j] = "NSP"
   else if (baseline$Adm12a[j] == "NN87" & baseline$Adm11[j] == 3)
    baseline$activproBis[j] = "R"

   ## 6
   else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 0)
     baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & (baseline$Adm10[j] %in% c(74,75,77,78) | is.na(baseline$Adm10[j])))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNN3NN" & baseline$Adm10[j] %in% c(74,77) )
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] %in% c(2,3))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] %in% c("NNN3NN", "N5NNNN") & baseline$Adm10[j] %in% c(74,77,95))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] == 77)
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & (baseline$Adm10[j] %in% c(74,75,77,78,85) | is.na(baseline$Adm10[j])))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(32,36))
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 95)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NN8N" & baseline$Adm11[j] == 5)
    baseline$activproBis[j] = "I"
  

  ## 7
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 0)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "N5NNNN" & baseline$Adm10[j] == 95)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(93,95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(86,77))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 2 & baseline$Adm12[j] == "N5NNNN" & baseline$Adm10[j] == 95)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 2 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(93,95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 2 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(86,74,77))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "N5NNNN" & baseline$Adm10[j] == 95)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(86,77))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "N5NNNN" & baseline$Adm10[j] %in% c(95,93))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(95,96,93))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,86))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NNN7" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 54)
    baseline$activproBis[j] = "NSP"
  
  ## 8
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 0 & baseline$Adm12[j] == "NNNNNN" & !(baseline$Adm10[j] %in% c(95,96,85,86,88)))
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 0 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 0 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(85,86,88))
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 0 & baseline$Adm12[j] != "6NNNNN")
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 0 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 0 & baseline$Adm12[j] == "6NNNNN" & !(baseline$Adm10[j] %in% c(95,96)))
    baseline$activproBis[j] = "T"

  
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 86)
    baseline$activproBis[j] = "I"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] ==54)
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 1 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] %in% c(36,61,66))
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 1 & !(baseline$Adm12[j] %in% c("NNNNNN", "6NNNNN")))
    baseline$activproBis[j] = "C"
    
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 2 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 2 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 86)
    baseline$activproBis[j] = "I"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 2 & baseline$Adm12[j] != "NNNNNN")
    baseline$activproBis[j] = "C" 
  
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(93,95,96))
    baseline$activproBis[j] = "C" 
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 74)
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] == 56)
    baseline$activproBis[j] =
      "NSP"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] %in% c("NNN3NN","N5NNNN","N5N3NN")) 
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] == 95)
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] %in% c(54,61))
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 3 & baseline$Adm12[j] == "65NNNN" & baseline$Adm10[j] == 54)
    baseline$activproBis[j] = "C"

  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(74,77,85,86))
    baseline$activproBis[j] = "R"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "NNNNNN" & baseline$Adm10[j] %in% c(32,36,47,48,51,54,55))
    baseline$activproBis[j] = "NSP"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & !(baseline$Adm12[j] %in% c("NNNNNN" , "6NNNNN", "65NNNN")))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "6NNNNN" & baseline$Adm10[j] == 54)
    baseline$activproBis[j] = "T"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 4 & baseline$Adm12[j] == "65NNNN" & baseline$Adm10[j] %in% c(95,96))
    baseline$activproBis[j] = "C"
  else if (baseline$Adm12a[j] == "NNNN" & baseline$Adm11[j] == 5 )
    baseline$activproBis[j] = "I"


}
```

```{r}
baseline$activproBis = as.factor(baseline$activproBis)
baseline$activproBis = relevel(baseline$activproBis , ref = "T")
```


```{r}
summary(baseline$activproBis)
```

```{r}
na_activproBis_id = baseline$nepp3[which(is.na(baseline$activproBis))]
```




