```{r}
print("activpro")
summary(baseline$activpro)
print("activproBis")
summary(baseline$activproBis)
print("activproCAH")
summary(baseline$activproCAH)
```

#Comparaison activpro et activproBis
```{r}
length(which(baseline$activpro != baseline$activproBis))
```
```{r}
print("repartition des 270 dans activpro")
summary(baseline$activpro[which(baseline$activpro != baseline$activproBis)])
print("repartition des 270 dans activproBis")
summary(baseline$activproBis[which(baseline$activpro != baseline$activproBis)])
```
Tendance à classer plus facilement en chômeurs et en reraite et plus difficilement en inactifs.
Le surplus va en NSP.

```{r}
summary(baseline$Adm12a[which(baseline$activpro != baseline$activproBis)])
summary(baseline$Adm11[which(baseline$activpro != baseline$activproBis)])
summary(baseline$Adm12[which(baseline$activpro != baseline$activproBis)])
summary(baseline$Adm10[which(baseline$activpro != baseline$activproBis)])
```
#comparaison activproBis et activproCAH
```{r}
length(which(baseline$activproCAH != baseline$activproBis))
(length(which(baseline$activproCAH != baseline$activproBis))/dim(baseline)[1])*100
```
```{r}
summary(baseline$activproBis)
```
```{r}
summary(baseline$activproCAH)
```
```{r}
baseline$activproBis = factor(baseline$activproBis, c("T","R","C","I","NSP",NA))
baseline$activproCAH = factor(baseline$activproCAH, c("T","R","C","I","NSP",NA))
```

## bar plot comparaison activproBis et activproCAH en %
```{r}
activproCAH_prop = (table(baseline$activproCAH)/10157)*100
actvproBis_prop = (table(baseline$activproBis)/10157)*100

comp_activpro_prop = rbind(actvproBis_prop,activproCAH_prop)

barplot(as.matrix(comp_activpro_prop), col = theme2l , beside = TRUE, main = "Comparaison des deux codages \n de la variable activpro (%)", xlab='classes activpro', ylab='Pourcentage')
legend("right", legend = c("activproManuel","activproCAH"), col='black', pch = c(20), pt.bg = theme2l, bty ='n')



```
## bar plot comparaison activproBis et activproCAH en effetcifs
```{r}
summary(baseline$activproBis)
summary(baseline$activproCAH)
```

```{r}


activproCAH_eff = table(baseline$activproCAH)
actvproBis_eff = table(baseline$activproBis)

comp_activpro_eff = rbind(actvproBis_eff,activproCAH_eff)

barplot(as.matrix(comp_activpro_eff), col = theme2lBis , beside = TRUE, main = "Comparaison des deux codages \n de la variable activpro (effectifs)", xlab='classes activpro', ylab='Effectifs')
legend("topright", legend = rownames(comp_activpro_eff), col='black', pch = c(22), pt.bg = theme2lBis, bty ='n')
```



# Etude des NSP

```{r}
tab = table(baseline$activproCAH[which(baseline$activproBis == "NSP")])
tab
```



```{r}
ggplot(baseline[which(baseline$activproBis == "NSP"),], aes(x = baseline$activproCAH[which(baseline$activproBis == "NSP")])) + 
  geom_bar(stat = "count", fill = "blue") + 
  xlab("Classes de la variable activproBis") + 
  ylab("Nombre d'observation par classe") + 
  ggtitle("CAH des individus classifiés comme NSP lors de la classification à la main\n n = 113")  + 
  theme_classic() + 
  annotate("text", "T", 35, label = "31") + 
  annotate("text", "R", 10, label = "5") +
  annotate("text", "I", 79, label = "77")

```








```{r}
summary(baseline$activproCAH[which(baseline$activproBis == "NSP")])
```


