---
title: "DATA"
output: html_notebook
---
##Library
```{r}
library(ggplot2)
library(FactoMineR)
library(ade4)
library(fastcluster)
library(cluster)
library(TeachingDemos)
library(Distance)
library(factoextra)
library(cowplot)
library(questionr)

```
## Data
```{r}
getwd()

# !!! MON ORDI !!!
baseline = read.csv(file = "C:/Users/odeli/Desktop/data/inclusion/Baseline.csv", header = TRUE, row.names = NULL, sep = ';')

# !!! ordi bureau !!!

#suivi_6 = read.csv(file = "W:/Odélia/srh_retraite/data/6_ans/suivi6.csv", header = TRUE, row.names = NULL, sep = ";")
#suivi_4 = read.csv(file = "W:/Odélia/srh_retraite/data/4_ans/suivi4.csv", header = TRUE, row.names = NULL, sep = ";")
```
## Themes

```{r}
theme2lbleu <- c( rgb(102,0,255, maxColorValue = 255),
              rgb(49,140,231, maxColorValue = 255))
```
```{r}
theme2lrouge <- c( rgb(115,8,0, maxColorValue = 255),
              rgb(219,23,2, maxColorValue = 255))
```

##Changement de type

### Activpro
```{r}
baseline$Adm10 = as.factor(baseline$Adm10)
baseline$Adm11 = as.factor(baseline$Adm11)
baseline$Adm12 = as.factor(baseline$Adm12)
baseline$Adm12a = as.factor(baseline$Adm12a)
baseline$Adm12a[which(baseline$Adm12a == "")] = NA
baseline$Adm12[which(baseline$Adm12 == "")] = NA
baseline$Adm11[which(baseline$Adm11 == "")] = NA
baseline$Adm10[which(baseline$Adm10 == "")] = NA
baseline$activpro = as.factor(baseline$activpro)
baseline$activproBis = as.factor(baseline$activproBis)
baseline$activproCAH = as.factor(baseline$activproCAH)
```


## Data intermediaires

```{r}
baselineP = baseline[-(which(baseline$nepp3 %in% na_activpro_id)),]

baselineP1 = baselineP[-(which(baselineP$nepp3 %in% na_srh_id)),]

baselineP2 = baselineP1[-(which(baselineP1$nepp3 %in% outliers_age_id)),]

baselineP3 = baselineP2[-(which(baselineP2$nepp3 %in% na_entourage_id)),]

baselineP4 = baselineP3[-(which(baselineP3$nepp3 %in% na_tabac_id)),]
```

## Gestion des exclus

```{r}
exclus_id = unique(c(na_activpro_id, na_srh_id, outliers_age_id, na_entourage_id, na_tabac_id))
length(exclus_id)
```
```{r}
length(intersect(exclus_id,na_tabac_id))
```

```{r}
exclus = baseline[which(baseline$nepp3 %in% exclus_id),]
dim(exclus)
```
```{r}
#compareGroups(baseline,exclus)
```

