---
title: "R Notebook"
output: html_notebook
---


```{r}
names(database)
```

```{r}
model1 = glm(srhBin ~activproBis + sexe , data = BASE2, family = 'binomial')
odds.ratio(model1)
```



```{r}
model2 = glm(srhBin ~ activproBis + sexe + age0Cut , data = BASE2, family = 'binomial')
odds.ratio(model2)
```


```{r}
(2018+1095)/(8+88+1095+2018)
```


######### variables style de vie

```{r}
aic_sante_phy = step(fit_null, direction = "both", scope = ~ activproBis + sexe + age0Cut + alcoolCut + tabac + diab + hta + bmiCut+ sport2 , trace = F)
summary(aic_sante_phy)
aic_sante_phy
```
##################anté psy

```{r}
aic_sante_psy = step(fit_null, direction = "both", scope = ~ activproBis + sexe + age0Cut + deptot+ stress , trace = F)
summary(aic_sante_psy)
```


############ variables socio admin

```{r}
aic_var_sa = step(fit_null, direction = "both", scope = ~ activproBis + sexe + age0Cut + csp + education + entourage , trace = F)
summary(aic_var_sa)
```
```{r}
aic_var_sa$formula
```

```{r}
aic_sante_phy$formula
```
```{r}
aic_sante_psy$formula
```
```{r}
baseSansEcxlus$activproBis = relevel(baseSansEcxlus$activproBis, ref = "T")
baseSansEcxlus$sexe = relevel(baseSansEcxlus$sexe, ref = "H")
baseSansEcxlus$csp = relevel(baseSansEcxlus$csp, ref = "Intermediaire")
baseSansEcxlus$education = relevel(baseSansEcxlus$education, ref = "CAP/Brevet des collèges")
baseSansEcxlus$entourage = relevel(baseSansEcxlus$entourage, ref = "couple")
baseSansEcxlus$sport2 = relevel(baseSansEcxlus$sport2, ref = 1)
baseSansEcxlus$bmiCut = relevel(baseSansEcxlus$bmiCut, ref = "normal")
#baseSansEcxlus$hta = relevel(baseSansEcxlus$hta, ref = 0)
baseSansEcxlus$tabac = relevel(baseSansEcxlus$tabac, ref = "non_fum")
#baseSansEcxlus$deptot = relevel(baseSansEcxlus$deptot, ref = 0)

```
```{r}
summary(baseSansEcxlus$deptot)
```

```{r}
model_final = glm(srhBin ~ activproBis + sexe + csp + education + entourage + sport2 + bmiCut + hta + tabac + deptot+ stress, family = "binomial", data = baseSansEcxlus)
odds.ratio(model_final)
```

```{r}
fit_null = glm(srhBin ~ 1, data = baseSansEcxlus, family = "binomial")
summary(fit_null)
```



