---
title: "Codage variable activpro"
output: html_notebook
---

---
title: "Encodage var"
output: html_notebook
---


Pour creer la variable on fixe comme variables principales Adm12a et Adm11 puis on "ajuste" avec Adm12 et Adm10

```{r}
table(baseline$Adm12a, baseline$Adm11, useNA = "ifany")
```


```{r}
baseline$activpro = 0
for(i in 1:(dim(baseline)[1])){
  
  if(is.na(baseline$Adm12a[i]))
    baseline$activpro[i] = NA

  else if (baseline$Adm12a[i] == "JNNN" & baseline$Adm11[i] == 0)
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "JNNN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "6NNNNN")
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "JNNN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "NNNNNN")
    baseline$activpro[i] = "AR"

  else if (baseline$Adm12a[i] == "N98N" & baseline$Adm10[i] == 85 & baseline$Adm12[i] != "NNN3NN")
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "N98N" & baseline$Adm10[i] == 85 & baseline$Adm12[i] == "NNN3NN")
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "N98N" & baseline$Adm10[i] != 85)
    baseline$activpro[i] = "R"

  else if (baseline$Adm12a[i] == "N9N7")
    baseline$activpro[i] = "AR"
  
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "N5N3NN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "N5NNNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "NNN3NN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(85,86))
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] != 0 & baseline$Adm12[i] == "NNNNNN" & (baseline$Adm10[i] %in% c(54,74,77) | is.na(baseline$Adm10[i])))
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] == 0 & baseline$Adm10[i] %in% c(85,86))
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "N9NN" & baseline$Adm11[i] == 0 & baseline$Adm10[i] == 77)
    baseline$activpro[i] = "AR"

  else if (baseline$Adm12a[i] == "NN87")
    baseline$activpro[i] = "AR"
  

  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 0 & baseline$Adm12[i]  == "6NNNNN")
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & (is.na(baseline$Adm10[i]) | baseline$Adm10[i] == 85))
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN"& baseline$Adm10[i] %in% c(74,75,77,78))
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 36)
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNN3NN")
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNNNNN")
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 2 & (baseline$Adm10[i] %in% c(74,75,77,78) | is.na(baseline$Adm10[i])))
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 2 & baseline$Adm10[i] == 85)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 3)
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 4 & baseline$Adm12[i] != "NNNNNN")
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & (baseline$Adm10[i] %in% c(74,75,77,78) | is.na(baseline$Adm10[i])))
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 85)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(32,36,95))
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 5 & baseline$Adm10[i] == 85)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NN8N" & baseline$Adm11[i] == 5 & baseline$Adm10[i] == 77)
    baseline$activpro[i] = "AR"

  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 0 & baseline$Adm12[i] != "NNNNNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(36,56))
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(85,86,93,95))
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "N5NNNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 86)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 77)
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(93,95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "N5NNNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(93,95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 86)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 74)
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 3 & baseline$Adm12[i] == "N5NNNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 3 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 3 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 86)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 3 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 77)
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "N5NNNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 54)
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(85,86))
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNN7" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(93,95,96))
    baseline$activpro[i] = "C"

  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(31,32,34,36,37,41,46,47,48,51,53,54,55,56,61,66))
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(74,77))
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(85,86))
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & is.na(baseline$Adm10[i]))
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 88)
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNN3NN" & baseline$Adm10[i] == 48)
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] == "NNN3NN" & baseline$Adm10[i] != 48)
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] %in% c("NN4NNN", "NN43NN" , "N5NNNN", "N5N3NN"))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 0 & baseline$Adm12[i] %in% c("6NNNNN", "6NN3NN", "6N43NN", "65NNNN", "65N3NN"))
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(54,95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 1 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 86)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 1 & baseline$Adm12[i] %in% c("NNN3NN", "NN4NNN", "NN43NN", "N5NNNN", "N5N3NN", "N543NN"))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 1 & baseline$Adm12[i] %in% c("6NNNNN", "6NN3NN", "6N4NNN", "6N43NN", "65NNNN", "65N3NN"))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 86)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 2 & baseline$Adm12[i] %in% c("NNN3NN", "N5NNNN", "N5N3NN"))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 2 & baseline$Adm12[i] == "6NN3NN")
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 3 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] == 56)
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 3 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] != 56)
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 3 & baseline$Adm12[i] %in% c("NNN3NN", "N5NNNN", "N5N3NN"))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 3 & baseline$Adm12[i] %in% c("65NNNN", "6NNNNN"))
    baseline$activpro[i] = "T"
  
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(77,74))
    baseline$activpro[i] = "R"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(95,96))
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(85,86))
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNNNNN" & baseline$Adm10[i] %in% c(55,54,51,48,47,36,32))
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NN4NNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNN3NN" & baseline$Adm10[i] == 85)
    baseline$activpro[i] = "AR"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NNN3NN" & baseline$Adm10[i] != 85)
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NN4NNN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "NN43NN") ## !!
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "N5NNNN" & baseline$Adm10[i] == 86)
    baseline$activpro[i] = "I"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "N5NNNN" & baseline$Adm10[i] != 86)
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] == "N5N3NN")
    baseline$activpro[i] = "C"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 4 & baseline$Adm12[i] %in% c("6NNNNN" , "65NNNN"))
    baseline$activpro[i] = "T"
  else if (baseline$Adm12a[i] == "NNNN" & baseline$Adm11[i] == 5 & baseline$Adm12[i] %in% c("N5NNNN", "N5N3NN"))
    baseline$activpro[i] = "C"
  
}
```

# Reduction AR

 Avant la reduction du nombre d'AR:
 
  AR    C    I    R    T 
  73  819  402 3155 5692 
  
  
Essayons de réduire le nombre de AR

```{r}
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNNN" & baseline$Adm11 == 4 & baseline$Adm12 == "NNNNNN")] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNNN" & baseline$Adm11 == 4)] = "C"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNNN" & baseline$Adm11 == 3)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNNN" & baseline$Adm11 == 0 & baseline$Adm10 == 88)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNNN" & baseline$Adm11 == 0 & baseline$Adm10 == 48)] = "T"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNN7" &  baseline$Adm11 == 0 & baseline$Adm10 %in% c(85,86))] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNN7" &  baseline$Adm11 == 0 & baseline$Adm10 %in% c(93,95))] = "C"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NNN7" & baseline$Adm11 == 4)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 5)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 4 & baseline$Adm12 == "NNNNNN" & baseline$Adm10 %in% c(32,36))] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 4 & baseline$Adm12 == "NNNNNN" & baseline$Adm10 == 95)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 4 & baseline$Adm12 == "NNN3NN")] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 4 & baseline$Adm12 == "6NNNNN")] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 4 & baseline$Adm12 == "N5NNNN")] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 1)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN8N" & baseline$Adm11 == 0)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN87" & baseline$Adm11 == 0)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "NN87" & baseline$Adm11 == 3)] = "R"
baseline$activpro[which(baseline$Adm12a == "N9NN" & baseline$Adm11 == 4 & baseline$Adm10 %in% c(77,74))] = "I"
baseline$activpro[which(baseline$Adm12a == "N9NN" & baseline$Adm11 == 4 & baseline$Adm10 == 54 )] = "NSP"
baseline$activpro[which(baseline$Adm12a == "N9NN" & baseline$Adm11 == 4 & is.na(baseline$Adm10))] = "I"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "N9NN" & baseline$Adm11 == 0)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "N9N7" & baseline$Adm11 == 4)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "N9N7" & baseline$Adm11 == 3)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "N9N7" & baseline$Adm11 == 1)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "N98N" & baseline$Adm11 == 4)] = "NSP"
baseline$activpro[which(baseline$activpro == "AR" & baseline$Adm12a == "JNNN" & baseline$Adm11 == 4)] = "NSP"
```


# FINAL TOUCH

```{r}
baseline$activpro = as.factor(baseline$activpro)
baseline$activpro = relevel(baseline$activpro , ref = "T")
```

# Gestion des NA
```{r}
summary(baseline$activpro)
```

```{r}
na_activpro_id = baseline$nepp3[which(is.na(baseline$activpro))]
```

