---
title: "Variable age0"
output: html_notebook
---

```{r}
summary(baseline$age0)
```
```{r}
sum(is.na(baseline$age0))
```


```{r}
baseline$logAge0 = log(baseline$age0)
```

```{r}
ggplot(baseline, aes(x = baseline$age0, color = baseline$sexe)) + geom_histogram(fill="black", position="dodge")+
  theme(legend.position="top") + ggtitle("Distribution de l'âge en fonction du sexe dans la cohorte epp3 \n n = 10157")
```


```{r}
library(ggplot2)
ggplot(baseline[which(baseline$sexe == "F"),], aes(x = baseline$age0[which(baseline$sexe == "F")])) + geom_histogram(fill = "pink", color = "red") + ggtitle("Distibution du log de l'âge des femmes")
```

```{r}
library(ggplot2)
ggplot(baseline[which(baseline$sexe == "H"),], aes(x = baseline$age0[which(baseline$sexe == "H")])) + geom_histogram(fill = "green", color = "blue") + ggtitle("Distibution du log de l'âge des femmes")
```
#gestion des na et outliers

```{r}
sum(is.na(baseline$age0))
```
```{r}
length(which(baseline$age0 > 76))
```
```{r}
baseline$age0[which(baseline$age0 > 76)]
```
```{r}
length(baseline$age0[which(baseline$age0 < 50)])
```
```{r}
outliers_age_id = baseline$nepp3[which(baseline$age0 > 76 | baseline$age0 < 50)]
```

## Classes d'âge
```{r}
sum(is.na(baselineP2$age0))
```

```{r}
summary(baselineP2$age0)
```

```{r}
baseline$age0Cut = cut(baseline$age0, breaks = quantile(baseline$age0), right = T)
summary(baseline$age0Cut)
```
```{r}

```


```{r}
baseline$age0Cut = cut(baseline$age0, breaks = c(0,58,59,60,61,62,64,65,70,75,90), right = FALSE)
summary(baseline$age0Cut)
```

```{r}
ggplot(baseline, aes(factor(baseline$activproBis,c("R","I","C","T","NSP",NA)), baseline$age0, fill = baseline$activproBis))+ 
  geom_boxplot() +
  xlab("Activité Professionelle") +
  ylab("Âge") +
 scale_fill_jama(name="",
                         breaks=c("R", "I", "C","T","NSP",NA),
                         labels=c("Retraités", "Inactifs", "Chômeurs","Travailleurs","Ne Sais Pas","NA"))



```

